project_id = "aqkdbnaxapjkmthzmrye"

[functions.send-contact-email]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.save-chat-lead]
verify_jwt = false
